version: '3'

services:
  app:
    container_name: wallet-service
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14
    env_file: .env
    ports: 
      - 5433:${POSTGRES_PORT}
    expose: 
      - ${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pg_data:

